name = "conerkicks-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"



[[d1_databases]]
binding = "DB"
database_name = "conerkicks-db"
database_id = "7108af93-707b-46cf-8a70-9be933810001"
migrations_dir = "../../packages/db"
